export const ROUTES = {
    SIGN_IN: 'sign-in',
    SIGN_UP: 'sign-up',
    FORGOT_PASSWORD: 'forgot-password',
    ABOUT: 'about',
    CHAT: 'chat',
    PROFILE: 'profile',
    SETTINGS: 'settings',
    CATALOG: 'catalog',
    INVESTORS: 'investors',
    RISK_OVERVIEW: 'risk-overview-overview',
    LEGAL: 'legal',
    PRIVACY: 'privacy',
    ACCOUNT: 'account',
    IMPRINT: 'imprint',
    MY_RISKS: 'my-risks',
    MY_BIDS: 'my-bids',
}
